### ISSUE TITLE
Library Arduino

### ISSUE THREAD

**Issue by ekonom22** [someburner/esp-rfm69#1]
Hello,
I very like ESP8266. I'm using Arduino IDE.
Can You transform ESP-RFM69 to Arduino Library (of course for ESP)?

Regards,
Damian

**Comment by someburner** [comment]
Damian,

Unfortunately I don't think that is possible with the current Esp-Arduino project. I originally tried to do a more-or-less direct port of Felix Rusu's RFM69 driver (compiled for Arduino), but I was not able to get hardware SPI to function properly. However this was some time ago, and I've learned a lot about the RFM69 and ESP8266 since then. I'm fairly busy, but sometime in the future I can probably try looking over the Esp-Arduino code again and see if it's possible. 

I'll leave this open and confirm one way or the other when I get time.

**Comment by ekonom22** [comment]
Hello,
Thank for your reply.
For your information: [about port nRF for ESP8266](https://github.com/TMRh20/RF24/issues/125).

Regards,
Damian

**Comment by someburner** [comment]
Thanks for that. 

Looks like someone got it working using the same pins as mine. I'll still have to go through and re-write it using the esp-arduino SPI methods and determine the best way to handle interrupts and buffers, but it seems doable. I'm busy for now but maybe next week! 

Also, the OTA firmware updates may require some extra work. If that's not important to you I can probably do basic send/receive stuff pretty easily.

**Comment by bkenobi** [comment]
Did you get this working?  I'm also looking to use this library to create a RFM69 to WiFi gateway using the Arduino IDE and your library sounds like it's very close to what I need.  I tried to compile it into my project, but there were a lot of dependencies.  I can go through and update things so I get everything included as necessary but if the library is not designed to work with this setup I don't want to waste my time.

My setup is using:
Arduino IDE, NodeMCU v3 (ESP-12E), RFM69HW

**Comment by bkenobi** [comment]
Since there haven't been any updates in 4 months is it fair to say this project is considered complete?  I'm still searching for an Arduino IDE library for the RFM69 that would compile for the ESP12E and your effort seems like the closest option.  I would take on the task, but I don't have the technical skills required so I know it would never happen.

**Comment by someburner** [comment]
I will be updating the project soon. However the likelihood of an Arduino port from me is slim. I simply have no need to use Arduino framework with the ESP8266. Sorry about that.
