### ISSUE TITLE
A few issues with compiling

### ISSUE THREAD

**Issue by janchrillesen** [someburner/esp-rfm69#3]
I just found this project and tried to build it on Ubuntu Linux, and found the following issues:

I needed to "sudo apt-get install zlib1g-dev openjdk-8-jre" to get zlib.h and java
I needed to "mkdir tools/spiffy-compressor/spiffy/build" (from topdirectory) for the build to complete
The documentation could be more clear with regards to that "make clean-spiffy" + "make spiffy" needs to be run from the topdir, and not from the tools/spiffy-compressor directory
The Makefile doesn't mention anything on how to compile 868 MHz support (which is a big thing here in Europe!) - I assume 86 will work
When defining FLASH_INIT_DEFAULT + FLASH_BLANK the associated .bin files needs to be copied from SDK bin dir to esp-rfm69

All in all not big issues, but you may consider fixing in next release

Looking forward to actually test the code

**Comment by someburner** [comment]
Thank you for jumping through the hoops to get it compiled! Part of the issue is that this release is a modified version of a private repo which is where I do most of the development. I also just haven't had time to clean up the makefile and make certain parts optional, add error messages/suggestions, stuff like that.

Yes, you should be fine using 868 MHz. As well as 433 or 315. And yes, the define should be set to 86 as per include/driver/rfm69.h

Looking forward to hearing your results! In the meanwhile, I will address your comments and update the makefile and documentation accordingly. There is also a lot of things I could/should document better to help people understand the 'internal API' I've implemented.

**Comment by janchrillesen** [comment]
Hi Jeff,
For various reasons I haven't done any testing until today, and I haven't had much luck (flashing the code the the ESP8266 works fine and I can access the webinterface). I have tested with an Anarduino and an Arduino Pro Mini, using the examples from Felix' RFM69 driver (both modules uses RFM69CW). One thing I notice is that the README file indicates that DIO0 should be connected to GPIO5, while the console output says 

GPIO2 set interrupt mode
GPIO2 enable (UP) mode

So, I'm a bit confused - should I use GPIO2 or GPIO5 for DIO0?

Also, did you find the time to work on the documentation? I was looking at how to configure MQTT but wasn't able to connect to my broker

**Comment by janchrillesen** [comment]
Brief update - If I try to send data from the radio console, it seems to work randomly. If I press send 20 times my Arduino node may receive 1 or 2 packets. Nothing gets back, but if the code really expects DIO0 on GPIO2 it's obvious why I don't receive anything on the ESP8266

**Comment by someburner** [comment]
Yeah so you need to go into driver/rfm69.c and change which pin to interrupt on. Or perhaps that's in the makefile. But I believe the debug statements saying which pin the interrupt is attached to is correct. However, I would recommend using GPIO5, as opposed to 2, because 2 should have a pullup and that could interfere with the operation of the interrupts. It's kind of confusing since some ESP-12's have GPIO4/5 marked incorrectly. But yes if I remember correctly if the pin is not set right it may be able to send, but you won't see any RX packets. DIO0 is actually used for both Tx and Rx in the RFM69 driver so it is important to set it correctly.

**Comment by someburner** [comment]
In the makefile, you need to change:
RFM_INTR_PIN = X
where X is the **pin number**. Note that the pin number is NOT the same as the GPIO number. For that, go into app/driver/gpio16.c and you will see at the top a list of which pin number corresponds to which GPIO. So 2 is actually GPIO4 which is what I use for my setups. If you want GPIO5 you must set it to 1

**Comment by someburner** [comment]
Also the front-end web stuff is a bit buggy, but should work for the most part. I know for sure that the wifi page needs to be re-worked and the filesystem page crashes sometimes or doesn't repopulate correctly.

**Comment by janchrillesen** [comment]
Thanks Jeff, setting RFM_INTR_PIN to 2 and using physical GPIO4 did it. Now I see traffic going back and forth my ESP8266 and my Arduino. 
What is the status of the MQTT implementation? I notice that the README basically says "More to come..." - ideally I would like a setup where I could use publish/subscribe to send and receive messages using MQTT, for instance publishing to esp/2 would send a message to node ID 2 with the payload of the MQTT message
Also, do you have local commits that's not pushed to github, that you expect to push soon, or should I just work with the current release for now? TIA

**Comment by someburner** [comment]
Glad you got it working!

And yeah, the library in there right now is this one: https://github.com/tuanpmt/esp_mqtt
It's not properly implemented right now, since I had to mangle it to push the public release, but you should be able to clear most the changes I've made with that and just start with a fresh version. Basically I originally released this as a sort of proof-of-concept in hopes that it would attract more people to the whole ESP8266<->RFM69 thing. But I'm developing stuff on a private repo for my startup and I don't have time to sift through all the commits and choose which ones I can allow to be public and which ones I can't, unfortunately. However, most of the app-level APIs I made, like generateRfmTxMsg() and all the web stuff, have not changed much at all since the last push. 

I was planning on making another tab on the web app that handles MQTT stuff. But what you're asking should be pretty easy to implement so I can probably do another update with MQTT and some bug-fixes. What kinds of things would you like to see? And just send out pubs or would it be good to show sub'd messages in the log too?

And if you just need some barebones MQTT stuff and no web console I can probably get something up pretty quick.

**Comment by janchrillesen** [comment]
What I'm looking for is a simple RFM69<->MQTT gateway and I have no use for the webinterface, as I prefer to put all logic in a central place (like domoticz or openhab). So a solution that will publish all received messages from a specific node to a specific topic, and let a specific node subscribe to a specific topic. Something similar to the project described here: https://harizanov.com/2015/11/rfm69-to-mqtt-gateway-using-esp8266/
As there seem to have been very little interessent in your project I understand why you want to focus your work on your startup

**Comment by someburner** [comment]
OK I'll try to have something out this week. Im working on mqtt again on the other repo so it shouldn't be long.

**Comment by someburner** [comment]
@janchrillesen Just pushed a basic thing for MQTT. I didn't implement the calls in rfm_parser.c yet but basically you just need to set your MQTT settings and then use mqtt_api_pub() in rfm_parser whenever you want to send the message out. And then in the MQTT onDataCB you need to do an create rfm message or whatever you want to do
